### PR TITLE
Use @code-hike/lighter

### PR DESCRIPTION
**Pull request by pomber**
<details>
  <summary>📦 Published PR as canary version: <code>0.8.0--canary.308.6cc554b.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @code-hike/mdx@0.8.0--canary.308.6cc554b.0
  # or 
  yarn add @code-hike/mdx@0.8.0--canary.308.6cc554b.0
  ```
</details>

### CODE REVIEW

**Comment by bkase** [comment]
fyi I'm able to get basic fenced code blocks to work on my React18/Next13/Contentlayer project with this branch. But I am getting errors when I try to use any CodeHike components in my mdx files.

```
[0] TypeError: Cannot read properties of undefined (reading 'length')
[0]     at InnerCode (webpack-internal:///(sc_client)/./node_modules/@code-hike/mdx/dist/components.esm.mjs:3450:21)
[0]     at renderWithHooks (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7681:16)
[0]     at renderIndeterminateComponent (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7755:15)
[0]     at renderElement (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7990:7)
[0]     at renderNodeDestructiveImpl (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8157:11)
[0]     at renderNodeDestructive (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8129:14)
[0]     at renderIndeterminateComponent (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7809:7)
[0]     at renderElement (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7990:7)
[0]     at renderNodeDestructiveImpl (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8157:11)
[0]     at renderNodeDestructive (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8129:14)
[0]     at renderNode (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8313:12)
[0]     at renderChildrenArray (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8265:7)
[0]     at renderNodeDestructiveImpl (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8194:7)
[0]     at renderNodeDestructive (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8129:14)
[0]     at renderElement (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8016:9)
[0]     at renderNodeDestructiveImpl (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8157:11)
[0]     at renderNodeDestructive (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8129:14)
[0]     at renderIndeterminateComponent (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7809:7)
[0]     at renderElement (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7990:7)
[0]     at renderNodeDestructiveImpl (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8157:11)
[0]     at renderNodeDestructive (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8129:14)
[0]     at renderIndeterminateComponent (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7809:7)
[0]     at renderElement (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7990:7)
[0]     at renderNodeDestructiveImpl (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8157:11)
[0]     at renderNodeDestructive (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8129:14)
[0]     at renderNode (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8313:12)
[0]     at renderChildrenArray (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8265:7)
[0]     at renderNodeDestructiveImpl (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8194:7)
[0]     at renderNodeDestructive (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8129:14)
[0]     at renderNode (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8313:12)
[0]     at renderHostElement (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7665:3)
[0]     at renderElement (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7996:5)
[0]     at renderNodeDestructiveImpl (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8157:11)
[0]     at renderNodeDestructive (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8129:14)
[0]     at renderNode (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8313:12)
[0]     at renderHostElement (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7665:3)
[0]     at renderElement (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7996:5)
[0]     at renderNodeDestructiveImpl (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8157:11)
[0]     at renderNodeDestructive (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8129:14)
[0]     at renderIndeterminateComponent (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7809:7)
[0]     at renderElement (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7990:7)
[0]     at renderLazyComponent (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7970:3)
[0]     at renderElement (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8080:11)
[0]     at renderNodeDestructiveImpl (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8157:11)
[0]     at renderNodeDestructive (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8129:14)
[0]     at renderNode (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8313:12)
[0]     at renderChildrenArray (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8265:7)
[0]     at renderNodeDestructiveImpl (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8194:7)
[0]     at renderNodeDestructive (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8129:14)
[0]     at renderContextProvider (/Users/bkase/site3/site3/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7954:3)
```

Mdx here:

		<CHCode>
		
		```ocaml semigroup.ml focus=1[2:5]
		module type Semigroup = sig
		  type t
		
		  (* We don't use <> in the ML langs because <> is traditionally "is not equal" *)
		  val (+) : t -> t -> t
		end
		```
		
		```haskell semigroup.hs
		-- You can find this in Data.Semigroup
		class Semigroup a where
		  (<>) :: a -> a -> a
		```
		
		</CHCode>

slug.tsx:

```tsx
import { useMDXComponent } from "next-contentlayer/hooks"
import { CH } from "@code-hike/mdx/components"

const Mdx = ({ code } : {code: string}) => {
  const Component = useMDXComponent(code);

  return (
    <Component components={{
      CHCode: CH.Code
    }} />
  )
}
```

When I inspect `props` it looks like `props.children` has components that have the `files` key (upon which `length` is called).

**Comment by bkase** [comment]
If you could update the next+contentlayer example to use the CH components, that would be very helpful I think!

**Comment by pomber** [comment]
@bkase why are you aliasing `CH.Code` to `CHCode`? 

I tried adding your mdx but using `CH.Code` to `examples/contentlayer/posts/two.mdx` in this branch and it works.

**Comment by bkase** [comment]
@pomber I'm able to reproduce the bug on this example on `posts/two.mdx` -- note I had to tweak package.json to use the right versions of things.

https://github.com/bkase/codehike-contentlayer-bug

**Comment by bkase** [comment]
Okay I realized the bug is from trying to add the `CH` components when the `remarkCodeHike` plugin does this for you.

It seems to be working for me now!

**Pull request merged**
